### PR TITLE
Maelstrom Weapon

### LINKED ISSUE #701: Maelstrom Weapon Stacks do not reset after used
**Describe the bug**
Description in title.

**To Reproduce**
1. Go to the Shaman Enhancement (Season of Discovery) sim webpage.
2. Go to Gear and add the Maelstrom Weapon rune to any waist gear.
3. Set one enemy with 100 duration.
4. Go to Rotation and add a new action " Cast Chain Lightning", if Compare - Aura Num Stacks - Self - Maelstrom Weapon == Constant 5. 
5. See error in Results - Timeline: Maelstrom Weapon reaches 5 stacks and it never goes down again.

**Expected behavior**
Timeline should show Maelstrom Weapons stack dropping to zero after the cast of Chain Lightning.

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Firefox
 - Version 124.0.1

**Additional context**
The bug leads to unrealistic high DPS for Shaman.

### PR DESCRIPTION
**Pull request by vigo2**
[shaman] use SpellFlagMaelstrom for Maelstrom Weapon handling

This was intended to fix #701 but I couldn't repro that issue ;) So now it's a marginal perf increase, better than nothing.

### CODE REVIEW

File: sim/shaman/runes.go [hunk 1]
```diff
@@ -337,7 +319,7 @@ func (shaman *Shaman) applyWayOfEarth() {
 	}
 
 	// Way of Earth only activates if you have Rockbiter Weapon on your mainhand and a shield in your offhand
-	if shaman.Consumes.MainHandImbue != proto.WeaponImbue_RockbiterWeapon && (shaman.OffHand() == nil || shaman.OffHand().WeaponType != proto.WeaponType_WeaponTypeShield) {
+	if shaman.Consumes.MainHandImbue != proto.WeaponImbue_RockbiterWeapon && shaman.OffHand().WeaponType != proto.WeaponType_WeaponTypeShield {
```
Comment (Basskip) [inline sim/shaman/runes.go:322]: Should this condition be an OR? Rockbiter && Shield are required for activation, so to negate that and exit early it should be !Rockbiter || !Shield

Comment (vigo2) [reply sim/shaman/runes.go:322]: pre-existing, but yeah

**Review by kayla-glick — APPROVED** [review]
